{
 "title": "ZFS Quota Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "dataset",
    "label": "Dataset",
    "query": "SHOW TAG VALUES WITH KEY = \"fs\" WHERE host =~ /$server$/"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "SHOW TAG VALUES WITH KEY = \"username\" WHERE \"fs\" =~ /^$dataset$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Usage by Dataset",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_mount_point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select bytes_reference from zfs_quota where $timeFilter GROUP BY mount_point",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dataset Capacity Consumption Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_mount_point",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "quota",
     "query": "select bytes_reference from zfs_quota where $timeFilter GROUP BY mount_point",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Dataset Statistics (Select in Drop Down)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Dataset Block Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "select bytes_reference from zfs_quota where $timeFilter and mount_point =~ /${dataset:regex}$/",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  },
  {
   "title": "User Usage within Dataset",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_quota",
     "query": "select \"username\",bytes_used,obj_used from zfs_quota where fs =~ /${dataset:regex}$/ and quota_type = 'user' and $timeFilter",
     "select": [
      [
       { "params": [ "bytes_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "fs", "operator": "=~", "value": "/^$dataset$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Usage (Dataset Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select bytes_reference from zfs_quota where $timeFilter and mount_point =~ /${dataset:regex}$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iNodes Used (Project Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select obj_used from zfs_quota where $timeFilter and fs =~ /${dataset:regex}$/ and quota_type = 'project' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dataset iNode Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "select obj_used from zfs_quota where $timeFilter and fs =~ /${dataset:regex}$/ and quota_type = 'project' and $timeFilter",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Individual User Statistics Within Fileset (User/Fileset Selected in Drop Down)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Dataset iNode Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Used iNodes",
     "measurement": "quota",
     "query": "select obj_used from zfs_quota where fs =~ /${dataset:regex}$/ and quota_type = 'user' and $timeFilter and \"username\" =~ /$username$/",
     "select": [
      [
       { "params": [ "filesused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fileset$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" }
     ]
    }
   ]
  },
  {
   "title": "Dataset Block Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Used Bytes",
     "measurement": "quota",
     "query": "SELECT \"bytes_used\" FROM \"zfs_quota\" WHERE fs =~ /${dataset:regex}$/  AND \"username\" =~ /^$username$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "blockused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=", "value": "iccp" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FILESET" },
      { "condition": "AND", "key": "fileset", "operator": "=~", "value": "/^$fileset$/" }
     ]
    }
   ]
  }
 ]
}