{
 "title": "ZFS Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM zfs_pool WITH KEY = \"host\""
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "SHOW TAG VALUES FROM zfs_pool WITH KEY = \"pool\" WHERE host =~ /$server$/"
   },
   {
    "name": "dataset",
    "label": "Dataset",
    "query": "SHOW TAG VALUES FROM zfs_pool WITH KEY = \"dataset\" WHERE pool =~/$pool$/ and host =~ /$server$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Performance - Whole Server: $server",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Throughput - Whole Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(ReadPerf) from (select difference(read_bytes)/60 as \"ReadPerf\" from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sda/ GROUP BY \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(WritePerf) from (select difference(write_bytes)/60 as \"WritePerf\" from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sda/ GROUP BY \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOPs - Whole Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Read IOPs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rops) from (select difference(reads)/60 as rops from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write IOPs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(wops) from (select difference(writes)/60 as wops from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\") group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dataset Performance - Pool: $pool Dataset: $dataset",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Metadata Performance /${dataset}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(reads) as \"Read IOPs\", difference(writes) as \"Write IOPs\" from zfs_pool  where host =~ /$server$/ and  pool =~ /$pool$/ and dataset =~ /${dataset:regex}$/ and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput Performance /${dataset}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(nread)/60 from zfs_pool where $timeFilter and host =~ /$server$/ and host =~ /$server$/and pool =~ /$pool$/ and dataset =~ /${dataset:regex}$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(nwritten)/60 from zfs_pool where $timeFilter and host =~ /$server$/and pool =~ /$pool$/ and dataset =~ /${dataset:regex}$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Drive Performance", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(read_bytes)/60 from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(write_bytes)/60 from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(reads)/60 from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(writes)/60 from diskio where host =~ /$server$/ and $timeFilter and \"name\" =~ /sd.*[a-z]$|nvme.*n1$/ and \"name\" !~ /^sdm/ GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}